on: push

env:
  GO_VERSION_FILE: "go.mod"
  CHECK_LATEST: true

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        uses: actions/setup-go@v5
        with:
          go-version-file: ${{ env.GO_VERSION_FILE }}
          check-latest: ${{ env.CHECK_LATEST }}
      -
        name: Pull dependencies
        run: go mod vendor
      -
        name: Linter
        run: make lint
      -
        name: Unit tests
        run: make test
